FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances système
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copie des requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code
COPY . .

# Port Streamlit
EXPOSE 8501

# Commande par défaut
CMD ["streamlit", "run", "web-interface/streamlit-app/main.py", "--server.address", "0.0.0.0"]
